### PR TITLE
Added //update command and automatic use after WorldEdit edit

### LINKED ISSUE #60: Update redstone after //paste
Should update all redstone in the WE selection, send any feedback messages using the WE api

### PR DESCRIPTION
**Pull request by MiranCZ**
resolved #60

### CODE REVIEW

**Comment by Matthias1590** [comment]
I don't think we need the feature class, if we do we'll have to rewrite it to use the new core system

**Comment by MiranCZ** [comment]
I think having just the command is also useful. Like when you forget to turn the gamerule on

**Comment by Matthias1590** [comment]
True, are you ok with rewriting it? or should I? You can take a look at other features to see what changed, you basically have the arguments in the class now instead of a separate options class

**Comment by MiranCZ** [comment]
Yeah, I think it will be fine since this doesnt have any arguments

**Comment by MiranCZ** [comment]
It should be OK now

**Review by Matthias1590 — APPROVED** [review]

**Pull request merged**
