### PR TITLE
Made /glass convert all block from /colorcode

### LINKED ISSUE #96: Revise glass
- make blocks from forcecolorcode also change on glass
 - when invalid block, give white wool (could also be config option)

### PR DESCRIPTION
**Pull request by MiranCZ**
resolves #96 
I moved some methods from `ColorCodeFeature` to `BlockColorUtils` to eliminate code duplication

### CODE REVIEW

**Comment by Matthias1590** [comment]
The color code feature is currently being revised so I don't think modifying it is a good idea atm

**Comment by MiranCZ** [comment]
But I would use those methods anyway

**Comment by Matthias1590** [comment]
I'll merge the revisions first, we'll see if it creates any conflicts

**Comment by Matthias1590** [comment]
I'll merge the revisions first, we'll see if it creates any conflicts

**Comment by MiranCZ** [comment]
Alright

**Comment by MiranCZ** [comment]
Should be good to go now

**Comment by Matthias1590** [comment]
Is this still necessary now that the refactor branch is merged? Cause if so I'll merge once the conflicts are resolved, otherwise please close this pr

**Comment by MiranCZ** [comment]
Yes, this adds requests from #96

**Pull request closed without merging**
