### PR TITLE
Revised redstoner

### PR DESCRIPTION
**Pull request by RUGMJ**
added feedback in chat as if the player executed the gamerules themselves

### CODE REVIEW

**Comment by RUGMJ** [comment]
image

**Comment by Matthias1590** [comment]
Please make an issue before creating a pr next time. For the feedback, maybe it'd be better if it ran the commands instead of modifying the server object (the old way ran the commands) so it automatically generates the correct output

**Review by Matthias1590 — CHANGES_REQUESTED** [review]
Run commands instead of modifying world object

**Comment by MiranCZ** [comment]
Can't this just undo #54

**Comment by RUGMJ** [comment]
Surely this can be a revert of 823b5fc742f86b0d05cd11b80a2d2cac8e5b6bbb then?

**Comment by Matthias1590** [comment]
> > Please make an issue before creating a pr next time.
> 
> It was already discussed in the dev meeting so I thought putting something on the issue tracker would be unnecessary 

Having everything in one place keeps it clear what needs to be done and let's us assign people to tasks

**Comment by Matthias1590** [comment]
> Surely this can be a revert of 823b5fc742f86b0d05cd11b80a2d2cac8e5b6bbb then?

Probably, yes

**Comment by RUGMJ** [comment]
Sorry it took so long for such a simple fix, should be back to more active commits

**Review by Matthias1590 — APPROVED** [review]

**Pull request merged**
