### PR TITLE
Catched number format exception

### PR DESCRIPTION
**Pull request by RUGMJ**
Solves #43

### CODE REVIEW

**Review by Matthias1590 — CHANGES_REQUESTED** [review]
Try to only encapsulate the code that can fail in the try block, also what's the todo for?

**Comment by RUGMJ** [comment]
I don't think it really makes a difference, the todo was left there by mistake from my editor I'll push a commit to remove it now

**Comment by Matthias1590** [comment]
> I don't think it really makes a difference, the todo was left there by mistake from my editor I'll push a commit to remove it now

It does, if the sendFeedback method were to throw an exception that happened to be caught it would fail but for the wrong reason, try blocks should be as small as possible

**Comment by RUGMJ** [comment]
It's only catching number format errors so it wouldn't make a difference

**Comment by Matthias1590** [comment]
It's still considered bad practice, keeping try blocks small keeps the code readable

**Review by Matthias1590 — APPROVED** [review]

**Pull request merged**
